INSERT INTO rol (DESCRIPCION)
SELECT 'SECRETARIA'
    WHERE NOT EXISTS ( SELECT DESCRIPCION FROM rol WHERE DESCRIPCION = 'SECRETARIA');

INSERT INTO rol (DESCRIPCION)
SELECT 'ADMINISTRADOR'
    WHERE NOT EXISTS ( SELECT DESCRIPCION FROM rol WHERE DESCRIPCION = 'ADMINISTRADOR');

